-- How to add data by hand in DataGrip (or psql) - the ordering database
-- (dhaka_kacchi_ordering). Plain-English notes above each example; copy the
-- INSERT, change the values, run it.
--
-- GOLDEN RULES:
--   1. Run a SELECT to check what you're about to change BEFORE an UPDATE/DELETE.
--   2. Almost everything here is normally created BY THE WEBSITE ITSELF
--      (registering, logging in, placing an order). Only reach for a manual
--      INSERT when you're backfilling old data the site never saw.
--   3. If a statement fails with a "duplicate key" error on phone/email, that
--      value is already used by another account - Postgres is protecting you
--      from creating two accounts with the same phone or email.


-- =====================================================================
-- CUSTOMERS - an account
-- =====================================================================
-- Real accounts are created by registering on the site (with a real
-- verified phone number and a real password you never see). If you're
-- manually adding an old customer who never registered, you CANNOT give
-- them a working password by hand - a password has to go through the
-- app's own hashing. Instead:
--
--   1. Generate a placeholder hash (run this once, from the worker/ folder,
--      in a terminal - not in DataGrip):
--        node -e "require('bcryptjs').hash('not-a-real-password', 12).then(console.log)"
--      Copy the long "$2b$12$..." string it prints out.
--
--   2. Use that as password_hash below. The account is created but CANNOT
--      log in with any password yet - tell the customer to use
--      "Forgot password" (with their email) the first time, which sets a
--      real password only they know.
INSERT INTO customers
  (id, created_at, phone, email, password_hash, name, date_of_birth,
   address_street, address_house_number, address_postal_code, address_city)
VALUES (
  'cust_' || gen_random_uuid(),
  now()::text,
  '+491701234567',                 -- must be in +<country><number> format
  'old.customer@example.com',
  '$2b$12$PASTE_YOUR_GENERATED_HASH_HERE',
  'Jane Doe',
  '1990-05-14',                    -- YYYY-MM-DD
  'Alexanderstraße', '1', '10178', 'Berlin'
);


-- =====================================================================
-- ORDERS - backfilling an old order (rare - see warning)
-- =====================================================================
-- WARNING: placing a real order through the site does a lot more than one
-- INSERT - it checks the delivery date, computes the delivery fee from the
-- address, and re-derives every price from the menu. A manual insert skips
-- ALL of that, so only do this for historical record-keeping (e.g. an old
-- WhatsApp order you want on file), and double-check every number yourself.
INSERT INTO orders
  (id, created_at, delivery_date, fulfillment_type,
   customer_id, customer_name, customer_email, customer_phone,
   subtotal_cents, delivery_fee_cents)
VALUES (
  'ord_' || gen_random_uuid(),
  now()::text,
  '2026-08-01',                     -- must be a real past Saturday
  'pickup',                         -- 'pickup' or 'delivery'
  (SELECT id FROM customers WHERE email = 'old.customer@example.com'),
  'Jane Doe',
  'old.customer@example.com',
  '+491701234567',
  999,                               -- subtotal in CENTS (999 = €9.99)
  0                                  -- delivery fee in cents (0 for pickup)
);

-- Then add its line items (one row per item ordered):
INSERT INTO order_items (order_id, sku, name, unit_price_cents, quantity)
VALUES (
  (SELECT id FROM orders WHERE customer_email = 'old.customer@example.com' ORDER BY created_at DESC LIMIT 1),
  'kacchi_taster',
  'Kacchi Biriyani — Taster Box (750ml, 1 person)',
  999,
  1
);


-- =====================================================================
-- Tables you should NEVER insert into by hand
-- =====================================================================
-- `otp_codes`, `sessions`, `password_reset_tokens` only ever hold short-
-- lived, security-sensitive values (verification codes, login tokens,
-- password-reset links) generated by the app itself. There is no
-- legitimate reason to add a row here manually - if you need to fix a
-- customer's login problem, use the "Forgot password" flow on the site
-- instead.
