/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderRouteImport } from './routes/order'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as LocaleLayoutRouteImport } from './routes/$locale/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout.index'
import { Route as LocaleLayoutIndexRouteImport } from './routes/$locale/_layout.index'
import { Route as AdminLayoutReportingRouteImport } from './routes/admin/_layout.reporting'
import { Route as AdminLayoutPostPredictRouteImport } from './routes/admin/_layout.post-predict'
import { Route as AdminLayoutLoginRouteImport } from './routes/admin/_layout.login'
import { Route as AdminLayoutCockpitRouteImport } from './routes/admin/_layout.cockpit'
import { Route as LocaleLayoutSubscribeRouteImport } from './routes/$locale/_layout.subscribe'
import { Route as LocaleLayoutPrivacyRouteImport } from './routes/$locale/_layout.privacy'
import { Route as LocaleLayoutOrderRouteImport } from './routes/$locale/_layout.order'
import { Route as LocaleLayoutHistoryRouteImport } from './routes/$locale/_layout.history'
import { Route as LocaleLayoutAboutRouteImport } from './routes/$locale/_layout.about'
import { Route as AdminLayoutOrdersNewRouteImport } from './routes/admin/_layout.orders.new'

const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleLayoutRoute = LocaleLayoutRouteImport.update({
  id: '/$locale/_layout',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const LocaleLayoutIndexRoute = LocaleLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const AdminLayoutReportingRoute = AdminLayoutReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutPostPredictRoute = AdminLayoutPostPredictRouteImport.update({
  id: '/post-predict',
  path: '/post-predict',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutLoginRoute = AdminLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCockpitRoute = AdminLayoutCockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const LocaleLayoutSubscribeRoute = LocaleLayoutSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const LocaleLayoutPrivacyRoute = LocaleLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const LocaleLayoutOrderRoute = LocaleLayoutOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const LocaleLayoutHistoryRoute = LocaleLayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const LocaleLayoutAboutRoute = LocaleLayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleLayoutRoute,
} as any)
const AdminLayoutOrdersNewRoute = AdminLayoutOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscribe': typeof SubscribeRoute
  '/$locale': typeof LocaleLayoutRouteWithChildren
  '/admin': typeof AdminLayoutRouteWithChildren
  '/$locale/about': typeof LocaleLayoutAboutRoute
  '/$locale/history': typeof LocaleLayoutHistoryRoute
  '/$locale/order': typeof LocaleLayoutOrderRoute
  '/$locale/privacy': typeof LocaleLayoutPrivacyRoute
  '/$locale/subscribe': typeof LocaleLayoutSubscribeRoute
  '/admin/cockpit': typeof AdminLayoutCockpitRoute
  '/admin/login': typeof AdminLayoutLoginRoute
  '/admin/post-predict': typeof AdminLayoutPostPredictRoute
  '/admin/reporting': typeof AdminLayoutReportingRoute
  '/$locale/': typeof LocaleLayoutIndexRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/orders/new': typeof AdminLayoutOrdersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscribe': typeof SubscribeRoute
  '/$locale/about': typeof LocaleLayoutAboutRoute
  '/$locale/history': typeof LocaleLayoutHistoryRoute
  '/$locale/order': typeof LocaleLayoutOrderRoute
  '/$locale/privacy': typeof LocaleLayoutPrivacyRoute
  '/$locale/subscribe': typeof LocaleLayoutSubscribeRoute
  '/admin/cockpit': typeof AdminLayoutCockpitRoute
  '/admin/login': typeof AdminLayoutLoginRoute
  '/admin/post-predict': typeof AdminLayoutPostPredictRoute
  '/admin/reporting': typeof AdminLayoutReportingRoute
  '/$locale': typeof LocaleLayoutIndexRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/orders/new': typeof AdminLayoutOrdersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/history': typeof HistoryRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/subscribe': typeof SubscribeRoute
  '/$locale/_layout': typeof LocaleLayoutRouteWithChildren
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/$locale/_layout/about': typeof LocaleLayoutAboutRoute
  '/$locale/_layout/history': typeof LocaleLayoutHistoryRoute
  '/$locale/_layout/order': typeof LocaleLayoutOrderRoute
  '/$locale/_layout/privacy': typeof LocaleLayoutPrivacyRoute
  '/$locale/_layout/subscribe': typeof LocaleLayoutSubscribeRoute
  '/admin/_layout/cockpit': typeof AdminLayoutCockpitRoute
  '/admin/_layout/login': typeof AdminLayoutLoginRoute
  '/admin/_layout/post-predict': typeof AdminLayoutPostPredictRoute
  '/admin/_layout/reporting': typeof AdminLayoutReportingRoute
  '/$locale/_layout/': typeof LocaleLayoutIndexRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/orders/new': typeof AdminLayoutOrdersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/history'
    | '/order'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/subscribe'
    | '/$locale'
    | '/admin'
    | '/$locale/about'
    | '/$locale/history'
    | '/$locale/order'
    | '/$locale/privacy'
    | '/$locale/subscribe'
    | '/admin/cockpit'
    | '/admin/login'
    | '/admin/post-predict'
    | '/admin/reporting'
    | '/$locale/'
    | '/admin/'
    | '/admin/orders/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/history'
    | '/order'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/subscribe'
    | '/$locale/about'
    | '/$locale/history'
    | '/$locale/order'
    | '/$locale/privacy'
    | '/$locale/subscribe'
    | '/admin/cockpit'
    | '/admin/login'
    | '/admin/post-predict'
    | '/admin/reporting'
    | '/$locale'
    | '/admin'
    | '/admin/orders/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/history'
    | '/order'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/subscribe'
    | '/$locale/_layout'
    | '/admin/_layout'
    | '/$locale/_layout/about'
    | '/$locale/_layout/history'
    | '/$locale/_layout/order'
    | '/$locale/_layout/privacy'
    | '/$locale/_layout/subscribe'
    | '/admin/_layout/cockpit'
    | '/admin/_layout/login'
    | '/admin/_layout/post-predict'
    | '/admin/_layout/reporting'
    | '/$locale/_layout/'
    | '/admin/_layout/'
    | '/admin/_layout/orders/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HistoryRoute: typeof HistoryRoute
  OrderRoute: typeof OrderRoute
  OrdersRoute: typeof OrdersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SubscribeRoute: typeof SubscribeRoute
  LocaleLayoutRoute: typeof LocaleLayoutRouteWithChildren
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_layout': {
      id: '/$locale/_layout'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/$locale/_layout/': {
      id: '/$locale/_layout/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleLayoutIndexRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/admin/_layout/reporting': {
      id: '/admin/_layout/reporting'
      path: '/reporting'
      fullPath: '/admin/reporting'
      preLoaderRoute: typeof AdminLayoutReportingRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/post-predict': {
      id: '/admin/_layout/post-predict'
      path: '/post-predict'
      fullPath: '/admin/post-predict'
      preLoaderRoute: typeof AdminLayoutPostPredictRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/login': {
      id: '/admin/_layout/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLayoutLoginRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/cockpit': {
      id: '/admin/_layout/cockpit'
      path: '/cockpit'
      fullPath: '/admin/cockpit'
      preLoaderRoute: typeof AdminLayoutCockpitRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/$locale/_layout/subscribe': {
      id: '/$locale/_layout/subscribe'
      path: '/subscribe'
      fullPath: '/$locale/subscribe'
      preLoaderRoute: typeof LocaleLayoutSubscribeRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/privacy': {
      id: '/$locale/_layout/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocaleLayoutPrivacyRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/order': {
      id: '/$locale/_layout/order'
      path: '/order'
      fullPath: '/$locale/order'
      preLoaderRoute: typeof LocaleLayoutOrderRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/history': {
      id: '/$locale/_layout/history'
      path: '/history'
      fullPath: '/$locale/history'
      preLoaderRoute: typeof LocaleLayoutHistoryRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/$locale/_layout/about': {
      id: '/$locale/_layout/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleLayoutAboutRouteImport
      parentRoute: typeof LocaleLayoutRoute
    }
    '/admin/_layout/orders/new': {
      id: '/admin/_layout/orders/new'
      path: '/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminLayoutOrdersNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface LocaleLayoutRouteChildren {
  LocaleLayoutAboutRoute: typeof LocaleLayoutAboutRoute
  LocaleLayoutHistoryRoute: typeof LocaleLayoutHistoryRoute
  LocaleLayoutOrderRoute: typeof LocaleLayoutOrderRoute
  LocaleLayoutPrivacyRoute: typeof LocaleLayoutPrivacyRoute
  LocaleLayoutSubscribeRoute: typeof LocaleLayoutSubscribeRoute
  LocaleLayoutIndexRoute: typeof LocaleLayoutIndexRoute
}

const LocaleLayoutRouteChildren: LocaleLayoutRouteChildren = {
  LocaleLayoutAboutRoute: LocaleLayoutAboutRoute,
  LocaleLayoutHistoryRoute: LocaleLayoutHistoryRoute,
  LocaleLayoutOrderRoute: LocaleLayoutOrderRoute,
  LocaleLayoutPrivacyRoute: LocaleLayoutPrivacyRoute,
  LocaleLayoutSubscribeRoute: LocaleLayoutSubscribeRoute,
  LocaleLayoutIndexRoute: LocaleLayoutIndexRoute,
}

const LocaleLayoutRouteWithChildren = LocaleLayoutRoute._addFileChildren(
  LocaleLayoutRouteChildren,
)

interface AdminLayoutRouteChildren {
  AdminLayoutCockpitRoute: typeof AdminLayoutCockpitRoute
  AdminLayoutLoginRoute: typeof AdminLayoutLoginRoute
  AdminLayoutPostPredictRoute: typeof AdminLayoutPostPredictRoute
  AdminLayoutReportingRoute: typeof AdminLayoutReportingRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutOrdersNewRoute: typeof AdminLayoutOrdersNewRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutCockpitRoute: AdminLayoutCockpitRoute,
  AdminLayoutLoginRoute: AdminLayoutLoginRoute,
  AdminLayoutPostPredictRoute: AdminLayoutPostPredictRoute,
  AdminLayoutReportingRoute: AdminLayoutReportingRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutOrdersNewRoute: AdminLayoutOrdersNewRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HistoryRoute: HistoryRoute,
  OrderRoute: OrderRoute,
  OrdersRoute: OrdersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SubscribeRoute: SubscribeRoute,
  LocaleLayoutRoute: LocaleLayoutRouteWithChildren,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
